#!/bin/sh
set -e

assert_command() {
  if ! command -v $1 &> /dev/null; then
    echo "Missing command line utility: $1"
    exit 1
  fi
}

# Install the prezto zsh framework
if ! test -d $HOME/.config/zsh/.zprezto; then
  assert_command zsh
  zsh --no-rcs $HOME/.config/yadm/bootstrap-zsh
fi

assert_command systemctl
sh $HOME/.config/yadm/bootstrap-systemd
