#!/bin/sh -e

enable_user_service() {
  echo "Enabling user service: $1"
  systemctl --user enable --now $1
}

# Copy pam auth module for the autoexec service
sudo cp $HOME/.config/systemd/system/pam /etc/pam.d/$USER
# System wide service to autoexec the sway user service
echo "Copying local autoexec service file to system wide"
sudo cp $HOME/.config/systemd/system/autoexec@.service /etc/systemd/system/
echo "Enabling system service: autoexec@tty1"
systemctl enable autoexec@tty1

echo "Reloading the systemd user daemon"
systemctl --user daemon-reload

# Enable all complementary user serivces to sway
enable_user_service kanshi
enable_user_service swayidle
enable_user_service swaybg
enable_user_service foot
enable_user_service waybar
enable_user_service mako
enable_user_service wlsunset
