#!/bin/sh -e

assert_command() {
  if ! command -v $1 &> /dev/null; then
    echo "Missing command line utility: $1"
    exit 1
  fi
}

# Create the boot entry for the system
assert_command kesboot
sh $HOME/.config/yadm/bootstrap-kesboot

# Install the prezto zsh framework
if ! test -d $HOME/.config/zsh/.zprezto; then
  assert_command zsh
  zsh --no-rcs $HOME/.config/yadm/bootstrap-zsh
fi

# Setup systemd sleep & hibernate
sh $HOME/.config/yadm/bootstrap-sleep

assert_command systemctl
sh $HOME/.config/yadm/bootstrap-systemd

assert_command nmcli
sh $HOME/.config/yadm/bootstrap-networkmanager

assert_command intel-undervolt
sh $HOME/.config/yadm/bootstrap-undervolt
