#!/bin/sh

enable_user_service() {
  echo "Enabling user service: $1"
  systemctl --user enable --now $1
}

# System wide service to autoexec the sway user service
echo "Linking local autoexec service file to system wide"
systemctl link $HOME/.config/systemd/system/autoexec@.service
echo "Enabling system service: autoexec@tty1"
systemctl enable autoexec@tty1

COLOR=$(cat ${XDG_CONFIG_HOME:-$HOME/.config}/background)

# Enable all complementary user serivces to sway
enable_user_service kanshi
enable_user_service swaylock
enable_user_service swaybg@${COLOR}
enable_user_service foot
enable_user_service waybar
enable_user_service mako
enable_user_service wlsunset
