#!/bin/bash
# draw a terminal at the selected location (with slop)

read -r X Y W H < <(slop -f "%x %y %w %h" -b 4 -t 0 -q)

(( W -= 80 ))
(( H -= 80 ))

(( W /= 10 ))
(( H /= 24 ))

alacritty -d $W $H --position $X $Y
