#!/usr/bin/fish
# vim: set syntax=fish:

# local bar config
set WIDTH 140
set NAME "Batterybar"

set SCREEN_WIDTH (xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
set OFFSET_X (math "($BARS_MARGIN * 3) + 50")
set GEOMETRY {$WIDTH}x{$BARS_HEIGHT}+{$OFFSET_X}+{$BARS_MARGIN}
set bat_dir "/sys/class/power_supply/BAT0"

function out
  read -l capacity < "$bat_dir/capacity"
  read -l stat     < "$bat_dir/status"

  set s ""
  switch $stat
    case Full
      set s "f"

    case Discharging
      set s "d"

    case Charging
      set s "c"
  end 

  echo "%{c}$capacity% $s"
end

function loop
  while true
    out
    sleep 60
  end 
end

function spit
  loop &

  acpi_listen | while read -l line
    sleep 1
    out
  end 
end

spit | lemonbar -d -n "$NAME" -F "$BARS_FG" -B "$BARS_BG" \
  -g "$GEOMETRY" -f "$BARS_FONT" &

set wid (xdo id -m -a "$NAME")
xdo above -t "(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
