#!/bin/sh

hash herbstclient xrandr

print_tags() {
	for tag in $(herbstclient tag_status "$1"); do
		name=${tag#?}
		state=${tag%$name}
		case "$state" in
		'#')
			printf "%%{B${BG_1}} %s %%{B--}" "$name"
			;;
		'+')
			printf "%%{B${BACKGROUND}}%%{R} %s %%{R}%%{B-}" "$name"
			;;
		'!')
			printf "%%{B${RED}} %s! %%{B-}" "$name"
			;;
		'.')
			printf "%%{B${BACKGROUND}} %s %%{B-}" "$name"
			;;
		*)
			printf ' %s ' "$name"
		esac
	done
	printf '\n'
}

geom_regex='[[:digit:]]\+x[[:digit:]]\++[[:digit:]]\++[[:digit:]]\+'
geom=$(xrandr --query | grep "^$MONITOR" | grep -o "$geom_regex")
monitor=$(herbstclient list_monitors | grep "$geom" | cut -d: -f1)

print_tags "$monitor"

IFS="$(printf '\t')" herbstclient --idle | while read -r hook args; do
	case "$hook" in
	tag*)
		print_tags "$monitor"
		;;
	esac
done
