#!/bin/sh
SCREEN_WIDTH=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
SCREEN_HEIGHT=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)

HEIGHT=70
WIDTH=70
MARGIN=30
OFFSET_Y=$((SCREEN_HEIGHT - $HEIGHT - $MARGIN))


NAME="Leftbar"
bspc subscribe report | leftbar_panel | lemonbar -n "$NAME" -d -F#EBDBB2 -B#282828 -g ${WIDTH}x${HEIGHT}+${MARGIN}+${OFFSET_Y} -f "Operator Mono:size=12" &

wid=$(xdo id -m -a "$NAME")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
