#!/usr/bin/fish
# vim: set syntax=fish:

# local bar config
set WIDTH 50
set NAME "Leftbar"

set LEFT_MARGIN (math "$BARS_MARGIN * 2")
set GEOMETRY {$WIDTH}x{$BARS_HEIGHT}+{$LEFT_MARGIN}+{$BARS_MARGIN}

bspc subscribe report | leftbar_panel | lemonbar -d -n "$NAME" -F "$BARS_FG" \
  -B "$BARS_BG" -g "$GEOMETRY" -f "$BARS_FONT" &

set wid (xdo id -m -a "$NAME")
xdo above -t "(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
