#!/bin/sh
#
# set random photo as background with aestetics white print in the back
file=$(shuf -n1 -e $HOME/.config/wallpapers/*)

hsetroot -solid "#282828" -center $file # background
# hsetroot -solid "#ebdbb2" -center $file # foreground

# color=$(convert $file -resize 1x1 txt:- | grep -Po "#[[:xdigit:]]{6}")
# hsetroot -solid $color -center $file       # photo average color

# hsetroot -solid white -center $file     # white
