#!/bin/sh
#
# set random photo as background with aestetics white print in the back
file=$(shuf -n1 -e $HOME/.config/wallpapers/*)

# hsetroot -solid "#282828" -center $file # background
hsetroot -solid white -center $file     # white
# hsetroot -solid "#ebdbb2" -center $file   # foreground
