#!/bin/sh

SCREEN_WIDTH=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)

SCREEN_HEIGHT=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)

HEIGHT=70
WIDTH=70
MARGIN=30

OFFSET_X=$((SCREEN_WIDTH - $WIDTH - $MARGIN))
OFFSET_Y=$((SCREEN_HEIGHT - $HEIGHT - $MARGIN))

clock() {
  res=$(date "+%H:%M")

  echo "%{c}%{F#000000}$res"
}

spit() {
  while true; do
    clock
    sleep 30
  done
}

NAME="Rightbar"
spit | lemonbar -n "$NAME" -d -p -B#FFFFFF -g ${WIDTH}x${HEIGHT}+${OFFSET_X}+${OFFSET_Y} -f "Operator Mono:size=12" &

wid=$(xdo id -m -a "$NAME")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
