#!/usr/bin/fish
# vim: set syntax=fish:

# local bar config
set WIDTH 180
set NAME "Rightbar"

set SCREEN_WIDTH (xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
set OFFSET_X (math "$SCREEN_WIDTH - $WIDTH - ($BARS_MARGIN * 2)")
set GEOMETRY {$WIDTH}x{$BARS_HEIGHT}+{$OFFSET_X}+{$BARS_MARGIN}

rightbar_panel | lemonbar -d -n "$NAME" -F "$BARS_FG" -B "$BARS_BG" \
  -g "$GEOMETRY" -f "$BARS_FONT" &

set wid (xdo id -m -a "$NAME")
xdo above -t "(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
