#!/bin/sh
#
# Take a screenshot.

scr_dir=$HOME/Pictures/screens

date=$(date +%F)
time=$(date +%I-%M-%S)
file=$scr_dir/$date/$date-$time.jpg

mkdir -p "$scr_dir/$date"

import -compress Lossless $file
convert $file ${file%%.jpg}.png

cp -f "$file" "$scr_dir/current.jpg"
cp -f "${file%%.jpg}.png" "$scr_dir/current.png"

herbe "screen taken"
