#!/bin/bash
exe=`dmenu_path | grep -v  -f $HOME/.config/dmenu_ignores | dmenu`

if [ $exe = "chromium" ]; then
  if [ $(hostname) != "mbp" ]; then
      exec chromium --enable-features=WebUIDarkMode --force-dark-mode --force-device-scale-factor=1.1 %U
    else
      exec chromium --enable-features=WebUIDarkMode --force-dark-mode %U
    fi

    exit
fi

exec $exe
