#! /bin/sh

if ! pgrep -x "sxhkd" > /dev/null; then
  sxhkd &
fi

if ! pgrep -x "dunst" > /dev/null; then
  dunst &
fi

xset r rate 400 60
xsetroot -cursor_name left_ptr
hsetroot -cover .config/wallpaper.jpg

bspc monitor -d 1 2 3 4 5 6 

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.50

# colors from the gruvbox theme
# using color0 - unfocused ; color8 - focused
bspc config normal_border_color "#282828"
# active and focus are the same but on different monitors
bspc config active_border_color "#928374"
bspc config focused_border_color "#928374"

bspc config borderless_monocle   true
bspc config gapless_monocle      true

# make all the windows floating by default
bspc rule -a "*" state=floating
