#!/bin/sh

if ! pgrep -x "sxhkd" > /dev/null; then
  SXHKD_SHELL=bash sxhkd &
fi

if ! pgrep -x "picom" > /dev/null; then
  picom --config $HOME/.config/picom.conf &
fi

if ! pgrep -x "dunst" > /dev/null; then
  dunst &
fi

if ! pgrep -x "xob" > /dev/null; then
  # volume / brightness "progress-like" bar pipe
  # obtained with xob
  if [ -p "/tmp/xob" ]; then
    rm /tmp/xob
  fi
  mkfifo /tmp/xob

  tail -f /tmp/xob | xob &
fi

killall lemonbar 2>&1 > /dev/null
$HOME/.bin/leftbar &
$HOME/.bin/rightbar &

if [ -d "/sys/class/power_supply/BAT0" ]; then
  $HOME/.bin/batterybar &
fi

# brightness and volume default values
if command -v xbacklight; then
  xbacklight -set 25
fi

if command -v pamixer; then
  pamixer --set-volume 25
fi

xset r rate 400 60
xsetroot -cursor_name left_ptr
hsetroot -solid "#C3C3C3" #bg1
# hsetroot -cover .config/wallpaper.jpg

bspc monitor -d 1 2 3 4

bspc config border_width         0
bspc config window_gap           30 
bspc config split_ratio          0.50
bspc config top_padding          50

bspc config borderless_monocle   true
#bspc config single_monocle       true

bspc config gapless_monocle      true
# make all the windows floating by default
bspc rule -a "*" state=floating

# force windows on given screens
bspc rule -a "Chromium" desktop=^1 state=tiled
