version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 3307:8080

  db:
    image: mysql:5.6
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: o2